#!/usr/bin/env ruby

# This file is part of Crypt Underworld.
# 
# Crypt Underworld is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later
# version.
# 
# Crypt Underworld is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public
# License along with Crypt Underworld. If not, see
# <https://www.gnu.org/licenses/>.
# 
# Copyright (c) 2022 Zoë Sparks <zoe@milky.flowers>

# Vulkan has a lot of enums and bitflags and things with huge
# numbers of entries. As opposed to exposing these directly in
# our Vulkan API, I think it's nice to wrap them in our own
# types, mainly to insulate us a bit from changes in Vulkan's
# types but also for easier-to-read code on our side. Doing this
# entirely by hand isn't very practical because of how numerous
# these types are and how large some of them are, so this script
# exists to do some of the work automatically.
#
# You can pass this script a path to a `vulkan/vulkan.h` and it
# will generate a C++ header suitable for use as our
# `vulkan_util.hpp`. However, I intend for this script to be used
# "by hand"; I plan to use it by redirecting the results to a
# temporary file and comparing it with the existing
# `vulkan_util.hpp` using a diff tool. We won't really get the
# full benefit of the indirection if we just generate that header
# completely automatically; if Vulkan does change in ways we need
# to react to, we'll want to do that deliberately as part of the
# process of changing our header. Also, some of the functions
# provided by the header provide for getting text representations
# of Vulkan enum and bitflag values, and those can benefit from
# some direct human attention since they're meant for human
# consumption. Of course, if something about the output isn't
# right, edit this script instead of fixing the problem by hand.
#
# This script uses Nokogiri (https://nokogiri.org/) to parse
# `vk.xml`. If you have Ruby installed, you probably also have
# Nokogiri installed, but if not, `gem install nokogiri` should
# install it. In theory we could use Bundler here but I don't
# think Nokogiri has ever broken backwards compatability so right
# now I don't think it's really needed just for that one gem.

require_relative 'lib'

require 'optparse'

# Increases to the fractional part signify changes that don't affect the
# generated header.
#
# Increases to the whole part signify changes that alter the generated header.
Version = "1.0"

opt = OptionParser.new

DEFAULT_VK_XML_PATH = '/usr/share/vulkan/registry/vk.xml'

vk_xml_path =  DEFAULT_VK_XML_PATH

opt.on(
  '-x', '--vk-xml VK_XML',
  "path to vk.xml (without this flag, #{DEFAULT_VK_XML_PATH} is used)"
) {|path| vk_xml_path = path }

DEFAULT_HEADER_PATH = '../../include/vulkan_util.hpp'

$write_path = ''

opt.on(
  '-w', '--write [PATH]',
  "write the generated header to a file (#{DEFAULT_HEADER_PATH} without PATH)"
) do |path|
  if path
    $write_path = path
  else
    $write_path = DEFAULT_HEADER_PATH
  end
end

$stdout_out = false

opt.on(
  '-o', '--out', "write the generated header to stdout"
) { $stdout_out = _1}

$test_path = ''

opt.on(
  '-t', '--test [PATH]',
  "compare the generated header to the header at PATH and exit " \
  + "(#{DEFAULT_HEADER_PATH} without PATH)"
) do |path|
  if path
    $test_path = path
  else
    $test_path = DEFAULT_HEADER_PATH
  end
end

opt.parse!

$hdr_source = VulkanUtilHeader.new(vk_xml_path).generate

if !$test_path.empty?
  require 'minitest/autorun'

  class TestVulkanUtilHeaderCoarse < MiniTest::Test
    def test_matches_existing_vulkan_util_header
      existing_hdr = File.open($test_path, &:read)
      assert_equal existing_hdr, $hdr_source
    end
  end
elsif !$write_path.empty?
  File.open($write_path, 'w') { _1.puts $hdr_source }
elsif $stdout_out
  puts $hdr_source
else
  begin
    IO.popen(ENV['PAGER'], 'w') { _1.puts $hdr_source }
  rescue Errno::EPIPE
  end
end

exit 0
